<a href="https://colab.research.google.com/github/Elygledson/RedesNeurais/blob/main/Numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import numpy as np

# NumPy Array

# Create an empty array
emptyArray = np.empty(4, dtype=int)
print('empty array\n',emptyArray)
  
# Create a full array
fullArray = np.full((4), [1,2,3,4], dtype=int)
print('full array\n',fullArray)

empty array
 [1 1 1 1]
full array
 [1 2 3 4]


In [133]:
#Create a Numpy array filled with all zeros

zero = np.zeros(5, dtype=int)
print("array filled with all zeros\n", zero) 

#Create a Numpy array filled with all ones
ones = np.ones(5, dtype=int)
print("array filled with all one\n", ones) 

#Check whether a Numpy array contains a specified row

arr = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15]
                   ])

print('does the array contain [1, 2, 3, 4, 5]?\n',[1, 2, 3, 4, 5] in arr.tolist())

# How to Remove rows in Numpy array that contains non-numeric values?

array = np.array([[10, 11, 2],
                  [21, 0, 2],
                  [21, 0, np.nan]])
array = array[~np.isnan(array).any(axis=1)]
print('Delete all non-numeric elements\n',array)

#Remove single-dimensional entries from the shape of an array

print('Remove single-dimensional entries from the shape of an array')
a = np.array([[[2, 2, 2], [2, 2, 2]]])
   
print ("array a :", a) 
print("Shape of input array a : ", a.shape)  
  
n_array = np.squeeze(a) 
  
print ("output squeezed array : ", n_array)
print("Shape of output array : ", n_array.shape)

#Find the number of occurrences of a sequence in a NumPy array

array = np.array([[1, 2, 3, 4], 
                   [1, 4, 4, 5],
                   [4, 5, 7, 5]])

print('number of occurrences of a sequence ("4, 5") in a NumPy array',repr(array).count("4, 5"))

#Find the most frequent value in a NumPy array

array = np.array([1,4,3,4,3,3,3,4,1])
print("array")
print(array)
print("Most frequent value\n",np.bincount(array).argmax())

#Combining a one and a two-dimensional NumPy Array

x = np.arange(3)
print("One dimensional array")
print(x)
y = np.arange(6).reshape(2,3)
print("Two dimensional array")
print(y)
print('Combining a one and a two-dimensional NumPy Array')
for a, b in np.nditer([x,y]):
    print("%d:%d" % (a,b),)

#How to build an array of all combinations of two NumPy arrays?

a = np.array([1, 2])
b = np.array([4, 6])
print('How to build an array of all combinations of two NumPy arrays')
print("Array - a")
print(a)
  
print("Array - b")
print(b)
  

n_array = np.array(np.meshgrid(a, b)).T.reshape(-1, 2)
  
print("Combine array:")
print(n_array)

#How to add a border around a NumPy array?

array = np.ones((2, 2))
  
print('array before\n',array)
  
# constructing border of 0 around 2D identity matrix
# using np.pad()
array = np.pad(array, pad_width=1, mode='constant',
               constant_values=0)
  
print('0 on the border and 1 inside the array\n',array)

#How to compare two NumPy arrays?

array_a = np.array([1,3])
array_b = np.array([1,3])

comparison = array_a == array_b
ans = comparison.all()

print('are the vectors the same?',ans)

#How to check whether specified values are present in NumPy array?

array = np.array([0,1,2,3])
print('is the number 2 present in array?',2 in array)

#How to get all 2D diagonals of a 3D NumPy array?

array = np.arange(3 * 4 * 4).reshape(3, 4, 4) 
  
print("Original 3d array:\n",  
      array) 
diag = np.diagonal(array,  
                       axis1 = 1, 
                       axis2 = 2) 
  
print("2d diagonal array:\n",  
      diag)

#Flatten a Matrix in Python using NumPy

y = np.array([[2,3], [4,5]])
print('Matrix before\n',y)
print('Flatten a Matrix in Python using NumPy\n',y.flatten());

#Flatten a 2d numpy array into 1d array

y = np.array([[2,3,6], [4,5,6]])
print('Matrix before\n',y)
print('Flatten a 2d numpy array into 1d array\n',y.flatten());

#Move axes of an array to new positions

array = np.zeros((2, 3, 4))
print('Move axes of an array to new positions\n',np.moveaxis(array, 0, -1).shape)
print(np.moveaxis(array, -1, 0).shape)

#Interchange two axes of an array

array = np.array([[1,2,3]])
print('array before',array)
y =  np.swapaxes(array,0,1)
print('array after\n',y)

#NumPy – Fibonacci Series using Binet Formula

print('Fibonacci Series using Binet Formula')

a = np.arange(1, 11)
lengthA = len(a)

sqrtFive = np.sqrt(5)
alpha = (1 + sqrtFive) / 2
beta = (1 - sqrtFive) / 2

Fn = np.rint(((alpha ** a) - (beta ** a)) / (sqrtFive))
print("The first {} numbers of Fibonacci series are {} . ".format(lengthA, Fn))

#Counts the number of non-zero values in the array

a = np.array([[0, 1, 0, 0],
              [4, 1, 0, 0]])
print('non-zero values\n',np.count_nonzero(a))
#Count the number of elements along a given axis

array = np.array([[1, 2, 4, 1], [5, 1, 2, 4]])
print('array\n',array)
print(np.size(array, 0))
print(np.size(array, 1))

#Trim the leading and/or trailing zeros from a 1-D array

array = np.array((0, 0, 1, 1, 1, 4, 3, 2, 1, 3, 9, 0, 10, 0, 0))
  
ans = np.trim_zeros(array, 'b')
print('returns an array without any trailing  zeros\n',ans)

#Change data type of given numpy array

array_int = np.array([1,2,3,4,5])
print('before changing\n',array_int)
  
print('type',array_int.dtype)

array_float = array.astype('float64')
  
print('after changing\n',array_float)
  
print('type\n',array_float.dtype)

#Reverse a numpy array

array = np.array([1,2,3,4,5])
print('array before\n',array)
print('reverse array\n',array[::-1])

#How to make a NumPy array read-only?

array = np.zeros(5)
array.flags.writeable = False
print("Try to change the first element:")
##array[0] = 1


array filled with all zeros
 [0 0 0 0 0]
array filled with all one
 [1 1 1 1 1]
does the array contain [1, 2, 3, 4, 5]?
 True
Delete all non-numeric elements
 [[10. 11.  2.]
 [21.  0.  2.]]
Remove single-dimensional entries from the shape of an array
array a : [[[2 2 2]
  [2 2 2]]]
Shape of input array a :  (1, 2, 3)
output squeezed array :  [[2 2 2]
 [2 2 2]]
Shape of output array :  (2, 3)
number of occurrences of a sequence ("4, 5") in a NumPy array 2
array
[1 4 3 4 3 3 3 4 1]
Most frequent value
 3
One dimensional array
[0 1 2]
Two dimensional array
[[0 1 2]
 [3 4 5]]
Combining a one and a two-dimensional NumPy Array
0:0
1:1
2:2
0:3
1:4
2:5
How to build an array of all combinations of two NumPy arrays
Array - a
[1 2]
Array - b
[4 6]
Combine array:
[[1 4]
 [1 6]
 [2 4]
 [2 6]]
array before
 [[1. 1.]
 [1. 1.]]
0 on the border and 1 inside the array
 [[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]
are the vectors the same? True
is the number 2 present in array? True
Origi

In [ ]:
#Get the maximum value from given matrix
#Get the minimum value from given matrix
#Find the number of rows and columns of a given matrix using NumPy
#Select the elements from a given matrix
#Find the sum of values in a matrix
#Calculate the sum of the diagonal elements of a NumPy array
#Adding and Subtracting Matrices in Python
#Ways to add row/columns in numpy array
#Matrix Multiplication in NumPy
#Get the eigen values of a matrix
#How to Calculate the determinant of a matrix using NumPy?
#How to inverse a matrix using NumPy
#How to count the frequency of unique values in NumPy array?
#Multiply matrices of complex numbers using NumPy in Python
#Compute the outer product of two given vectors using NumPy in Python
#Calculate inner, outer, and cross products of matrices and vectors using NumPy
#Compute the covariance matrix of two given NumPy arrays
#Convert covariance matrix to correlation matrix using Python
#Compute the Kronecker product of two mulitdimension NumPy arrays
#Convert the matrix into a list#